Repository FZM-Technologies/Aquadroid, pull requests merged in 2023-04, with the labels that each got.

#5 Create Forking
  Forking
Labels: help wanted

#6 Update AquaOS.c
  AquaOS.c
Labels: invalid, Fixed

#23 Delete c-cpp.yml
  .github/workflows/c-cpp.yml
Labels: Code

#32 TasManager Debug Log Errors
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/generator-generic-ossf-slsa3-publish.yml
  AquaOS.c
  Forking
  README.md
Labels: Github, Error, Patch request, Low priority

#33 Revert "TasManager Debug Log Errors"
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/generator-generic-ossf-slsa3-publish.yml
  AquaOS.c
  Forking
  README.md
Labels: bug, Application, Code
